### ISSUE TITLE
Can't output expressions without evaluation

### ISSUE THREAD

**Issue by sylvainpolletvillard** [riot/tmpl#11]
Hello,

According to:  http://riotjs.com/guide/#printing-brackets ; we can output an expression without evaluation by escaping the opening brace:

          \\{ this is not evaluated \\} outputs { this is not evaluated }

I think it does not work anymore with 2.3 riot tmpl. Try on http://riotjs.com/play/ . What I got is :

         \\{ message \\} outputs \\{ message \\}

How can I output `{ message }` ?

**Comment by sylvainpolletvillard** [comment]
Thank you ☺

**Comment by aMarCruz** [comment]
@sylvainpolletvillard sorry, yesterday I forgot make click in a post to you.
This update is in npm too.
