### ISSUE TITLE
isRaw is returning false if the expression contains other text content before the template delimiters

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/tmpl#13]
The `isRaw` method must return `true` also if the expression is `text: {= rawMarkup }`. I have created a new branch adding the test for this bug `bug/isRaw`
Once this issue and [this](https://github.com/riot/riot/issues/1416) will be solved I will make a new riot release

**Comment by aMarCruz** [comment]
@GianlucaGuarini yes, it is only for expressions, `haveRaw` is for template and have its test. I thought I had mentioned it. Anyway, I will change the code for use `isRaw` only.
Just now I have problems with double-quote issues, the spaces is not the probleam, the double quotes is.
 
The compiler and tmpl use `brackets.split` which can deal with nested double quotes, the _real_ problem is in [this line](https://github.com/riot/riot/blob/master/lib/browser/tag/mkdom.js#L38) of `mkdom`. It injects the the html, then the expressions are readed [here](https://github.com/riot/riot/blob/master/lib/browser/tag/parse.js#L38) and in other parts through `getAttribute`, but at this point the browser already altered them (usually by dividing them into several nodes).

Till now I have identified 3 different behaviors depending on where they are in the markup, and 3 variations in interpretation depending on where you are going to use (including raw html).

(Also, [this regex](https://github.com/riot/riot/blob/master/lib/browser/tag/util.js#L291) in `walkAttributes` does not supports nested quotes inside the value. It needs `brackets.split` or another regex based in the `name=` part only (risky)).

Right now, I think the only solution is replacing double-quotes with another character that innerHTML does not alter, and revert it before the evaluation. I'm thinking in `U+2057` (Quadruple Prime, `&#8279;`).

After that, I'll start working on pre-compiled expressions, which should solve this problem.

Note: The same problem is for raw html (`<` and `>`) in attribute values.

**Comment by GianlucaGuarini** [comment]
@aMarCruz ok so I need to use `haveRaw` instead? If yes how should I treat the expressions like `Hi {= html } { normalText }`? Should I inject everything using `innerHTML`? Is this safe against XSS injections? [Here](https://github.com/riot/riot/blob/dev/lib/browser/tag/update.js#L95-L96) is where I have implemented the new tmpl feature is it correct?

 > Just now I have problems with double-quote issues, the spaces is not the probleam, the double quotes is.

We can skip this issue for now, it has low priority, let's focus on the raw markup that is a great improvement

**Comment by aMarCruz** [comment]
Yes, all as html. You can have both in a single node.
And you're right, I have enough the double quotes problem and you have many more :)

**Comment by GianlucaGuarini** [comment]
Ok so I will make a new release tonight using `haveRaw` that will render with innerHTML also the other expressions in the same node thank you

**Comment by aMarCruz** [comment]
@GianlucaGuarini ok, I will push a fix for double quotes to tmpl and compiler, with `isRaw` removed. Will be v2.3.19 in the dev branch, and a working plucker with a test here. If pass your test please publish, I will be out of home tomorrow.

**Comment by GianlucaGuarini** [comment]
Ok thanks @aMarCruz keep it easy

**Comment by aMarCruz** [comment]
@GianlucaGuarini , the dev branch of tmpl and compiler has the v2.3.19 already.
You can see in [this test](http://plnkr.co/edit/9i9T7v?p=preview) 4 cases, working with a custom version of riot+compiler using the new modules.

PS:
Your [previous question](https://github.com/riot/tmpl/issues/13#issuecomment-164366282) about [this line](https://github.com/riot/riot/blob/dev/lib/browser/tag/update.js#L95-L96): It is not so easy, the expression is in a '#text" node, i.e. doesn't have innerHTML.
You need insert another element as container for the new nodes coming from the raw html. If you use `parent.innerHTML = value` the expression and sibling nodes is lost. I think the new nodes can't be riot tags.

In my test, I used this:
```
    // text node
    if (!attrName) {
      if (tmpl.haveRaw(expr.expr)) {
        var id = dom._riot_rawId, box
        if (id) {
          box = $('span[_riot_id="' + id + '"]', dom.parentNode)
          // `dom` is moved inside its parent? if so, we need recreate box always
          if (box) dom.parentNode.removeChild(box)
        }
        box = mkEl('span')
        dom.parentNode.insertBefore(box, dom)
        dom._riot_rawId = id = id || ++__uid
        setAttr(box, '_riot_id', id)
        box.innerHTML = value
        value = ''
      }
      dom.nodeValue = '' + value    // #815 related
      return
    }
```
but I don't know if is ok, sure is not performant.

**Comment by GianlucaGuarini** [comment]
I would simply say that if you use `{= }` in the same node all the markup will be rendered as innerHTML

**Comment by GianlucaGuarini** [comment]
@aMarCruz I wrote you on skype

**Comment by GianlucaGuarini** [comment]
closing this in favor of https://github.com/riot/tmpl/issues/2#issuecomment-207800489
