### ISSUE TITLE
Each loops, __checked doesn't work

### ISSUE THREAD

**Issue by Javiani** [riot/tmpl#17]
I had that classic case when you want to append new elements in a list, considering that back-end already sets a initial amount of items on the page load, and the server is not node, could be anything, php, .net or whatever.

Virtual DOM really don't help me in this case, so I thought that would be a good idea to separate in  riot templates files, rendering new items on first user interaction.

The ideal scenario would be to use that format described in the docs, like `tmpl('', {})`. However, each loops and __checked properties are not evaluated at all, as result I had to loop over items in js and then replace string looking for __checked and removing the underlines...

I though that template system and riot was decoupled, but I can't get the same templating features I have using riot component approach.

**Comment by aMarCruz** [comment]
@Javiani , riot-tmpl is not the riot template engine, it is for evaluating the expressions (I know this is not a appropriate name :)).

If you have the data server-sive perhaps it is more performant and simpler to use pug or hogan/handlebars and delegate the logic in the client to riot (serving the riot tags precompiled).

**Comment by Javiani** [comment]
Hi @aMarCruz thanks for the feedback!

Ok then, good to know about riot-tmpl purposes. Thank you very much!
