### ISSUE TITLE
Yo can use brackets <% %> anymore

### ISSUE THREAD

**Issue by aMarCruz** [riot/tmpl#3]
This popular brackets from ASP looks great, but is causing many issues in riot.

ASP parses their files and then send the result to the html parser.
riot, by contrast, receives the tags from the html parser, probably altered. This is causing confusion to users that believe riot is a sort of ASP.

Also, the character `>` complicates the detection of tag elements, especially attributes. The compiler and tmpl are using the same function to separate expressions from markup: the new `brackets.split` function. `brackets.split` needs to be light because it must be included in riot, even without the compiler.

This new brackets function is the bridge between custom brackets, tmpl and the compiler, 'cause tmpl can receive the full body of a tag element and, practically, _compile_ it from scratch (think about `<yield>` as example).

**Comment by tipiirai** [comment]
I think we can drop the support for `< >` characters on custom brackets. I can see the challenges it causes. Just needs to be documented, that's all.
