### ISSUE TITLE
Unable to find tmpl.parse in the 2.3.0-beta.2 release

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/tmpl#4]
I have tried upgrading to the 2.3.0-beta.2 version but it seems that tmpl.parse is not defined. Am I doing something wrong?

**Comment by aMarCruz** [comment]
No, my error, it was for precompiled expressions, I update tmpl beta in npm with a fake parse function for not breaking current riot. I don't push updates to riot because having issues with test-karma. I'm working with fixing the compiler in browser, tests with karma do not pass.

**Comment by aMarCruz** [comment]
@GianlucaGuarini , tmpl is updated. The compiler take me more time, tracing the karma test is a nighmare. I don't have clear why karma test is using dist/riot and dist/compiler, and not riot+compiler, and loading with a eval().

**Comment by GianlucaGuarini** [comment]
@aMarCruz I will check why the tests don't worry. Just let me know when the compiler is ready and how exactly I should implement it in riot

**Comment by aMarCruz** [comment]
@GianlucaGuarini , yes. I upload a PR in the branch tmpl-23 working with the current tmpl release, fix a bug with brackets not updating, and includes riot.tag2 for the new compiler.

I need time for understand the different logic for generate tags on the server, the repercutions moving the compiler code out of the riot sources seems here, I think I have to generate 2 versions of the compiler for riot server and browser.

Please, apply PR and you can release 2.3, it is working with `tmpl 2.3.0-beta.7` and the old compiler. CLI has no problem with the new compiler, I will work on the browser/server side this days.

**Comment by aMarCruz** [comment]
btw: Please say to all it is better using `brackets.set()` instead `riot.settings.brackets` (or assign riot.settings to `brackets.settings`). Having `brackets` with riot as dependency makes difficult follow the changes. Maybe in the future we can standarize the use of `brackets.set`.

**Comment by GianlucaGuarini** [comment]
@aMarCruz cool thanks.. fixing the tests it seems to be harder than I thought

**Comment by aMarCruz** [comment]
Yeah :) and as we say in México: "me hice bolas"

**Comment by GianlucaGuarini** [comment]
After debugging the riot unit test on IE9/10/11 and Edge I found that the issues are coming from the new `riot-tmpl`. The test failing is the one on [this tag](https://github.com/riot/riot/blob/dev/test/tag/loop.tag) if I click the button there is no update on IE. I have created a new branch `bug/ie` where I have added the test failing.
To run the unit test on ie:
 1. run `make test`
 2. use browserstack to connect to the url provided by karma ( on my machine is http://localhost:9876/ )
 3. check the result of your tests in the terminal

p.s.
remember once you are done to set the `singleRun` to true again!

**Comment by GianlucaGuarini** [comment]
@aMarCruz screenshot of all the errors thrown on Edge
<img width="1235" alt="screen shot" src="https://cloud.githubusercontent.com/assets/879612/10703709/2ecbe6be-79d2-11e5-82bb-b68edddb54c3.png">

**Comment by aMarCruz** [comment]
thanks @GianlucaGuarini , thanks. I tracing this, the error is cause the optimizations. IE is given a blank rightContext in String.replace. only fix is remove the optimization. I'm out of city now, Monthay nigh I fix this.

**Comment by GianlucaGuarini** [comment]
I hope you are fine.. I have heard about the hurricane in Mexico! I will set up crossbrowser tests in this repo asap

**Comment by aMarCruz** [comment]
Yeah, we are all fine, it was little more than scare. Thanks.
